### ISSUE TITLE
composer network install -- card PeerAdmin@hlfv1 --archiveFile my-network@0.1.6.bna

### ISSUE THREAD

**Issue by Thanoos** [Aniket-Engg/Hyperledger-Medical-Network#3]
Unknown arguments: card, businessNetworkName, runtime, install
please help with this. How can I resolve this.

**Comment by Aniket-Engg** [comment]
@Thanoos Project was developed long time ago. To resolve the issues, latest tutorials may be helpful: https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html

**Comment by Thanoos** [comment]
Hi Aniket,
Many thanks for your reply. The network has been installed. The server is
running but it is giving error path not found. Can you please guide me on
this. I will be really thankful of you.

**Comment by Aniket-Engg** [comment]
> Hi Aniket, Many thanks for your reply. The network has been installed. The server is running but it is giving error path not found. Can you please guide me on this. I will be really thankful of you.

This is being tracked separately here: https://github.com/Aniket-Engg/Hyperledger-Medical-Network/issues/4

**Comment by Thanoos** [comment]
{"message":"failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","stack":"MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"error","timestamp":"Wed Jan 16 2019 18:11:30 GMT+0530 (IST)"}
{"message":"failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","stack":"MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"error","timestamp":"Wed Jan 16 2019 18:21:34 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Wed Jan 16 2019 18:30:26 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Wed Jan 16 2019 18:30:26 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Wed Jan 16 2019 18:30:56 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Wed Jan 16 2019 18:31:06 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Wed Jan 16 2019 18:39:25 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Wed Jan 16 2019 18:52:48 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Wed Jan 16 2019 18:53:06 GMT+0530 (IST)"}
{"message":"failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","stack":"MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"error","timestamp":"Thu Jan 17 2019 10:42:11 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 10:43:54 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 10:43:54 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 10:44:43 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 10:45:27 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:54:46 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:55:59 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:00 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:03 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:04 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:04 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:04 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:05 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:06 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:06 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:07 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:07 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:07 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:07 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 10:56:07 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 11:09:36 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 11:09:49 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 11:16:38 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:03:16 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:29:55 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:22 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:23 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:24 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:24 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:24 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:24 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:24 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:25 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:33:25 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:48 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:49 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:49 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:49 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:49 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:51 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:51 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:51 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:53 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:53 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:39:53 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:50 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:51 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:53 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 12:42:53 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 13:52:54 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 13:55:07 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 13:55:07 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 13:55:25 GMT+0530 (IST)"}
{"level":"error","message":"The path /test is not found","timestamp":"Thu Jan 17 2019 13:56:16 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Thu Jan 17 2019 14:00:16 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/singup is not found","timestamp":"Thu Jan 17 2019 14:00:32 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/signup is not found","timestamp":"Thu Jan 17 2019 14:00:45 GMT+0530 (IST)"}
{"level":"error","message":"The path /SampleAsset is not found","timestamp":"Thu Jan 17 2019 14:15:35 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/SampleAsset is not found","timestamp":"Thu Jan 17 2019 14:15:46 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Thu Jan 17 2019 14:26:05 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/index.js is not found","timestamp":"Thu Jan 17 2019 14:27:18 GMT+0530 (IST)"}
{"level":"error","message":"The path /api is not found","timestamp":"Thu Jan 17 2019 14:27:25 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 14:27:31 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 14:29:53 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 14:46:01 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 15:00:52 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 15:06:42 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 15:07:15 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 15:25:18 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 15:25:18 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 15:25:34 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Thu Jan 17 2019 15:25:59 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 15:27:16 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 15:32:56 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 15:40:02 GMT+0530 (IST)"}
{"level":"error","message":"The path / is not found","timestamp":"Thu Jan 17 2019 15:40:22 GMT+0530 (IST)"}
{"level":"error","message":"The path /api is not found","timestamp":"Thu Jan 17 2019 15:40:28 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 15:48:35 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 15:48:35 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Thu Jan 17 2019 15:49:04 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 15:49:54 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 15:49:54 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Thu Jan 17 2019 15:50:00 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 15:52:56 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 15:52:56 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/account is not found","timestamp":"Thu Jan 17 2019 15:53:44 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/network is not found","timestamp":"Thu Jan 17 2019 15:54:02 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/account/signup is not found","timestamp":"Thu Jan 17 2019 15:56:09 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/account/signup is not found","timestamp":"Thu Jan 17 2019 15:58:37 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 15:58:56 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 15:58:56 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/account/signup is not found","timestamp":"Thu Jan 17 2019 15:59:01 GMT+0530 (IST)"}
{"level":"error","message":"The path /account/signup is not found","timestamp":"Thu Jan 17 2019 15:59:46 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 16:01:39 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 16:01:39 GMT+0530 (IST)"}
{"level":"error","message":"The path /signup is not found","timestamp":"Thu Jan 17 2019 16:02:15 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 16:05:28 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 16:05:28 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/signup is not found","timestamp":"Thu Jan 17 2019 16:05:32 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 16:09:44 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 16:09:44 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/account/test1 is not found","timestamp":"Thu Jan 17 2019 16:10:05 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 16:12:30 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 16:12:30 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/account is not found","timestamp":"Thu Jan 17 2019 16:12:41 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 16:13:39 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 16:13:39 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/account is not found","timestamp":"Thu Jan 17 2019 16:13:47 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1 is not found","timestamp":"Thu Jan 17 2019 16:13:54 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 16:18:12 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 16:18:12 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/signup is not found","timestamp":"Thu Jan 17 2019 16:18:24 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Thu Jan 17 2019 17:22:33 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Thu Jan 17 2019 17:22:33 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Thu Jan 17 2019 17:22:57 GMT+0530 (IST)"}
{"message":"failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","stack":"MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/home/lsipl/Hyperledger-Medical-Network/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"error","timestamp":"Fri Jan 18 2019 10:27:41 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Fri Jan 18 2019 10:41:44 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Fri Jan 18 2019 10:41:44 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Fri Jan 18 2019 10:43:28 GMT+0530 (IST)"}
{"level":"info","message":"database successfully connected","timestamp":"Fri Jan 18 2019 12:34:23 GMT+0530 (IST)"}
{"level":"info","message":"Server running at http://localhost:5000/api/v1","timestamp":"Fri Jan 18 2019 12:34:23 GMT+0530 (IST)"}
{"level":"error","message":"The path /api/v1/ is not found","timestamp":"Fri Jan 18 2019 12:34:49 GMT+0530 (IST)"}
